config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dogs#index'
  resources :dogs do
    post :feed, on: :member
    post :walk, on: :member
    post :add_owner, on: :member
  end
  resources :feed_logs

  get 'zeus_guide', to: 'static_pages#zeus'

end

app/models/dog.rb
# == Schema Information
#
# Table name: dogs
#
#  id                   :integer          not null, primary key
#  name                 :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  picture_file_name    :string
#  picture_content_type :string
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#  sex                  :integer          default(0)
#

class Dog < ActiveRecord::Base
  has_many :ownerships
  has_many :users, through: :ownerships
  has_many :feed_logs
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ":style/default_dog.png"
  validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_with AttachmentSizeValidator, attributes: :picture, less_than: 3.megabytes
  enum sex: [:male, :female]
  validates :name, presence: true

  def feed_logs_today
    FeedLog.feed.where('time >= ? and dog_id = ?', DateTime.now.beginning_of_day, self.id)
  end

  def walk_logs_today
    FeedLog.walk.where('time >= ? and dog_id = ?', DateTime.now.beginning_of_day, self.id)
  end
  def logs_today
    FeedLog.where('time >= ? and dog_id = ?', DateTime.now.beginning_of_day, self.id).order(time: :desc)
  end

  def pronoun
    ["his", "her"][Dog.sexes[self.sex]]
  end
end

app/models/feed_log.rb
# == Schema Information
#
# Table name: feed_logs
#
#  id         :integer          not null, primary key
#  time       :datetime
#  dog_id     :integer
#  user_id    :integer
#  note       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  log_type   :integer          default(0)
#

class FeedLog < ActiveRecord::Base
  belongs_to :dog
  belongs_to :user
  enum log_type: [:feed, :walk]
  validates :time, :dog_id, :user_id, presence: true
end

app/models/ownership.rb
# == Schema Information
#
# Table name: ownerships
#
#  id         :integer          not null, primary key
#  dog_id     :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ownership < ActiveRecord::Base
  belongs_to :user
  belongs_to :dog

  validates_uniqueness_of :dog_id, scope: :user_id
  validates :dog_id, :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default("")
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string
#  invitations_count      :integer          default(0)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ownerships
  has_many :dogs, through: :ownerships

  def name
    if first_name
      first_name
    else
      email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name) }
    end
end

app/controllers/dogs_controller.rb
# == Schema Information
#
# Table name: dogs
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class DogsController < ApplicationController
  before_action :set_dog_and_check_owner!, only: [:show, :edit, :update, :feed, :add_owner, :walk]

  def index
    @dogs = current_user.dogs
  end

  def new
    @dog = Dog.new
  end

  def edit
  end

  def add_owner
    user = User.find_by_email(params[:user][:email])
    user ||= User.invite!({email: params[:user][:email]}, current_user)
    user.ownerships.build(dog_id: @dog.id).save
    flash[:notice] = 'User has been sent an invitation'
    redirect_to @dog
  end

  def update
    @dog.update(dog_params)
    redirect_to @dog
  end

  def feed
    @feed_log = FeedLog.new(dog_id: @dog.id)
    @feed_log.user = current_user
    @feed_log.time = DateTime.now
    @feed_log.save!
    redirect_to @feed_log.dog
  end

  def walk
    @feed_log = FeedLog.new(dog_id: @dog.id, log_type: 'walk')
    @feed_log.user = current_user
    @feed_log.time = DateTime.now
    @feed_log.save!
    redirect_to @feed_log.dog
  end

  def create
    @dog = Dog.create(dog_params)

    @ownership = current_user.ownerships.build(dog_id: @dog.id).save

    redirect_to dogs_path
  end

  def show
  end

  private

    def dog_params
      params.require(:dog).permit(:name, :sex, :picture)
    end

    def set_dog_and_check_owner!
      @dog = Dog.find(params[:id])

      ownership = Ownership.where(dog_id: @dog.id, user_id: current_user.id)

      unless ownership.present?
        flash[:alert] = 'You are not an owner of this pet'
        return redirect_to root_path
      end
    end

end

app/controllers/feed_logs_controller.rb
# == Schema Information
#
# Table name: feed_logs
#
#  id         :integer          not null, primary key
#  time       :datetime
#  dog_id     :integer
#  user_id    :integer
#  note       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  log_type   :integer          default(0)
#

class FeedLogsController < ApplicationController
  def create
    ownership = Ownership.where(dog_id: params[:feed_log][:dog_id], user_id: current_user.id)

    unless ownership
      flash[:alert] = 'You are not an owner of this dog'
      return redirect_to root_path
    end

    @feed_log = FeedLog.new(feed_log_params)
    @feed_log.user = current_user
    @feed_log.time = DateTime.now
    @feed_log.save!

    redirect_to @feed_log.dog
  end

  private

    def feed_log_params
      params.require(:feed_log).permit(:dog_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :authenticate_user!
  def zeus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
# == Schema Information
#
# Table name: dogs
#
#  id                   :integer          not null, primary key
#  name                 :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  picture_file_name    :string
#  picture_content_type :string
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#  sex                  :integer          default(0)
#

module DogsHelper
end

app/helpers/feed_logs_helper.rb
# == Schema Information
#
# Table name: feed_logs
#
#  id         :integer          not null, primary key
#  time       :datetime
#  dog_id     :integer
#  user_id    :integer
#  note       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  log_type   :integer          default(0)
#

module FeedLogsHelper
end

app/views/dogs/_form.html.haml
= simple_form_for @dog do |f|
  = f.input :name
  = f.input :sex, collection: ['male', 'female'], default: 'male'
  = f.input :picture, as: :file
  = f.button :submit

app/views/dogs/edit.html.haml
= render 'form'

app/views/dogs/index.html.haml
- @dogs.each do |dog|
  .row
    .col-md-8.col-md-offset-2.col-sm-12.col-xs-12
      .well
        .row
          .col-md-3
            .text-center
              %br/
              = image_tag dog.picture.url(:thumb)
            .text-center
              = link_to dog.name, dog, style: 'font-size:200%'
              %br/
          .col-md-9
            .row
              %br/
              .col-md-10.col-md-offset-1.col-xs-10.col-xs-offset-1
                = link_to  feed_dog_path(dog), method: :post, class: 'btn btn-primary btn-lg btn-block' do
                  .row
                    .col-md-4.col-sm-4.col-xs-4
                      %i.fa.fa-flash{style: 'padding-right:20px'}
                    .col-md-4.col-sm-4.col-xs-4
                      .text-center
                        Feed
                    .col-md-4.col-sm-4.col-xs-4
                      #{(dog.feed_logs_today.count)}
                      %i.fa.fa-long-arrow-right
                      #{(dog.feed_logs_today.count + 1)}
                %br/
                = link_to walk_dog_path(dog), method: :post, class: 'btn btn-success btn-lg btn-block' do
                  .row
                    .col-md-4.col-sm-4.col-xs-4
                      %i.fa.fa-leaf{style: 'padding-right:20px'}
                    .col-md-4.col-sm-4.col-xs-4
                      .text-center
                        Walk
                    .col-md-4.col-sm-4.col-xs-4
                      #{(dog.walk_logs_today.count)}
                      %i.fa.fa-long-arrow-right
                      #{(dog.walk_logs_today.count + 1)}
                %br/

app/views/dogs/new.html.haml
= render 'form'

app/views/dogs/show.html.haml
.panel.panel-primary
  .panel-heading
    %h1.panel-title Profile
    %span.pull-right.clickable
      .dropdown
        %i.fa.fa-caret-down#dropdownMenu1.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
        %ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdownMenu1"}
          %li
            = link_to 'Feed', feed_dog_path(@dog), method: :post
            = link_to 'Edit dog', edit_dog_path(@dog)
  .panel-body
    .row
      .col-md-4
        .panel.panel-default
          .panel-heading
            .text-center
              %b{style: 'font-size:250%'}= @dog.name
          .panel-body
            .text-center
              = image_tag @dog.picture.url(:medium)
            .text-center
              %h3 Owners
            %table.table.table-striped.table-bordered
              %thead
                %tr
                  %th Name
                  %th Email
              %tbody
                - @dog.users.each do |user|
                  %tr
                    - if user.first_name.present?
                      %td= user.name
                    -else
                      %td
                    %td= user.email
            = simple_form_for :user, method: :post, url: add_owner_dog_path(@dog), html: {class: 'form-inline'} do |f|
              .form-group
                = f.input :email, as: :string, required: false, input_html: {class: 'form-control'}, label_html: {style: 'padding-right:10px'}
              = f.button :submit, 'Add owner', class: 'btn btn-sm btn-primary'
      .col-md-8
        .row
          .col-md-6
            = link_to 'Feed', feed_dog_path(@dog), method: :post, class: 'btn btn-block btn-lg btn-default'
            %br/
            .well
              .text-center
                %h3 #{@dog.name} has been fed
                %h1{style: 'font-size:500%'}= @dog.feed_logs_today.count
                %h3 #{'time'.pluralize(@dog.feed_logs_today.count)} today.
          .col-md-6
            = link_to 'Walk', walk_dog_path(@dog), method: :post, class: 'btn btn-block btn-lg btn-default'
            %br/
            .well
              .text-center
                %h3 #{@dog.name} has been walked
                %h1{style: 'font-size:500%'}= @dog.walk_logs_today.count
                %h3 #{'time'.pluralize(@dog.walk_logs_today.count)} today.
        .panel.panel-info
          .panel-heading Logs
          .panel-body
            - @dog.logs_today.each do |log|
              %p
                = log.user.name
                - if log.walk?
                  %b walked
                - else
                  %b fed
                = log.dog.name
                %b #{time_ago_in_words log.time} ago
              %hr/

app/views/layouts/_navigation.html.haml
%header.navbar
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle{ :type => "button", :"data-toggle" => "collapse", :"data-target" => ".navbar-collapse" }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      .navbar-collapse.collapse
        %ul.nav.navbar-nav.navbar-left
          %li
            = link_to root_path, html_options = {:class =>'navbar-brand'} do
              %i.fa.fa-paw
              FEED THE DOG
        %ul.nav.navbar-nav.navbar-left
          - if user_signed_in?
            - current_user.dogs.each do |dog|
              %li=link_to dog.name, dog
          %li
            = link_to new_dog_path do
              %i.fa.fa-plus
              Add a dog
        %ul.nav.navbar-nav.navbar-right{role: "tablist"}
          - if user_signed_in?
            %li= link_to current_user.name, edit_user_registration_path
            %li= link_to 'Sign out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'Sign up', new_user_registration_path
            %li= link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Feedthedog2
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .col-md-12
            - if notice
              .alert.alert-info{role: 'alert'}= notice
            - if alert
              .alert.alert-warning{role: 'alert'}= alert
            = yield

app/views/static_pages/zeus.html.haml
.row
  .col-md-6
    %h1 Zeus the Timid Doggo
    %p Zeus comes with a carepackage! Items inlcuded are:
    %ul
      %li food (both wet and dry)
      %li food and water bowls
      %li bed with washable cover
      %li blanket
      %li various toys, both squeeky and silent
      %li treats for good boys
      %li cage with bedding
      %li leash
      %li harness
      %li shampoo
      %li poop bags
      %li old math team shirt
    %h2 Doggo's Daily Schedule
    %ol
      %li Take him out soon after you get up. You should use his harness for any walks.
      %li Feed him one scoop of dry food in the morning.
      %li Around lunch time feed him 1/2 of a wet food container, other half lives in the fridge.
      %li Take him out to pee.
      %li If he's eaten all of his food from earlier in the day, feed him the other half of the wet food at dinner time.
      %li Take him to poop after dinner.
      %li Give him a Greenie for his teeth. (Green treats shaped like a toothbrush)
      %li Take him out one last time before bed.
    %h2 Should I...
  .col-md-6
    %img{:src => "http://i.imgur.com/3ddWu4F.jpg"}
.row
  .col-md-6
    .well
      %h3 Yes!
      %ul
        %li Take Zeus on car rides? He loves em!
        %li Let Zeus on furniture? If the couch owner consents, Zeus loves being comfy.
        %li Throw his toys to play fetch? When he's in the mood, Zeus is a fetch fiend.
        %li Leave Zeus alone? He will cry a bit, but will be fine alone either in his cage or just in an enclosed space (any room with a door).
  .col-md-6
    .well
      %h3 No!
      %ul
        %li Leave Zeus in a car unattended? Even if the weather is nice or whatever, he hates this and will cry loudly.
        %li Play rough with Zeus? He's a big pup but will be afraid of you for at least 3 minutes if you try to chase/tackle him.
        %li Give Zeus human food? It's tempting because he's so cute and good at begging, but refrain for the good of all parties involved.
.row
  %h2 ZEUS FACTS
  %p  He gets cold with his new haircut. If you notice he's shivering, cover him with his blanket or put on his math team shirt.
  %p  Zeus is a flexible sleeper. His first choice is to sleep with you in a bed, second choice is the couch/futon, third choice is his dog bed, fourth is the cage. Do with this information what you will.
  %p He barks a lot when he's nervous. To avoid excessive borks, quietly let him know that you are there and can protect him by putting your face close to his and saying "quiet."
  %p Zeus LOVES treats.
  %p He will be fresh and clean when you get him but if for any reason you want to bathe him, do so in the shower. He will temporarily hate you for this.
  %p Peanut butter/dog treats in the Kong toy is the best way to keep Zeus busy.
  %p He has been eating his body like a corncob due to anxiety. If you catch him in the act, sternly tell him "No!"
  %p PLEASE save and share any pictures you might take of Zeus.